### ISSUE TITLE
Visiting other ppls accounts

### ISSUE THREAD

**Issue by MDeero** [sillvva/rpg-schedule-nuxt#22]
Visiting the link https://www.rpg-schedule.com/games/upcoming (or any other valid URL path) can get you in someone elses account. Right now I am seeing events of someone called "KennyHass" and i am not that guy. I could also edit games. It seems to just carry over the access of whoever just logged in recently.

**Comment by MDeero** [comment]
It seems the session id is not per session

**Comment by sillvva** [comment]
I am setting up a new bot in an isolated server for testing soon. The invite for that server will be coming soon if you want to help beta test.

**Comment by MDeero** [comment]
yeah sure
whatever i can help with
